### ISSUE TITLE
how to install nvidia apex

### ISSUE THREAD

**Issue by jinzishuai** [jinzishuai/3DC-Seg#2]
the package is here https://github.com/NVIDIA/apex

But `pip install apex` is https://pypi.org/project/apex/ which is a completely differnt project.

**Comment by jinzishuai** [comment]
```
(.venv) seki@LAPTOP-0OTVHE5I:~/ZeroBox/src/3DC-Seg$  python main.py -c run_configs/bmvc_fbms.yaml --task infer --wts ./bmvc_final.pth
Traceback (most recent call last):
  File "main.py", line 6, in <module>
    import apex
ModuleNotFoundError: No module named 'apex'
```

**Comment by jinzishuai** [comment]
# just checkout the code in the project folder does not work

```
(.venv) seki@LAPTOP-0OTVHE5I:~/ZeroBox/src/3DC-Seg$ ls
README.md      bmvc_final.pth  datasets            loss     network           run_configs  util.py
bmvc_fbms.zip  config          inference_handlers  main.py  requirements.txt  run_scripts  utils
(.venv) seki@LAPTOP-0OTVHE5I:~/ZeroBox/src/3DC-Seg$ git clone https://github.com/NVIDIA/apex.git
Cloning into 'apex'...
remote: Enumerating objects: 26, done.
remote: Counting objects: 100% (26/26), done.
remote: Compressing objects: 100% (26/26), done.
remote: Total 7939 (delta 5), reused 10 (delta 0), pack-reused 7913
Receiving objects: 100% (7939/7939), 14.02 MiB | 11.92 MiB/s, done.
Resolving deltas: 100% (5404/5404), done.
Updating files: 100% (312/312), done.
(.venv) seki@LAPTOP-0OTVHE5I:~/ZeroBox/src/3DC-Seg$ pip3 --version^C
(.venv) seki@LAPTOP-0OTVHE5I:~/ZeroBox/src/3DC-Seg$ python main.py -c run_configs/bmvc_fbms.yaml --task infer --wts ./bmvc_final.pth
Traceback (most recent call last):
  File "main.py", line 8, in <module>
    from apex import amp
ImportError: cannot import name 'amp' from 'apex' (unknown location)
(.venv) seki@LAPTOP-0OTVHE5I:~/ZeroBox/src/3DC-Seg$
```

**Comment by jinzishuai** [comment]
# 2. Follow instruction 

https://github.com/NVIDIA/apex#linux

```
(.venv) seki@LAPTOP-0OTVHE5I:~/ZeroBox/src$ git clone https://github.com/NVIDIA/apex
Cloning into 'apex'...
remote: Enumerating objects: 26, done.
remote: Counting objects: 100% (26/26), done.
remote: Compressing objects: 100% (26/26), done.
remote: Total 7939 (delta 5), reused 10 (delta 0), pack-reused 7913
Receiving objects: 100% (7939/7939), 14.02 MiB | 11.40 MiB/s, done.
Resolving deltas: 100% (5404/5404), done.
Updating files: 100% (312/312), done.
(.venv) seki@LAPTOP-0OTVHE5I:~/ZeroBox/src$ cd apex/
(.venv) seki@LAPTOP-0OTVHE5I:~/ZeroBox/src/apex$ ls
LICENSE  README.md  apex  csrc  docs  examples  requirements.txt  requirements_dev.txt  setup.py  tests
(.venv) seki@LAPTOP-0OTVHE5I:~/ZeroBox/src/apex$ pip install -v --disable-pip-version-check --no-cache-dir --global-option="--cpp_ext" --global-option="--cuda_ext" ./
```

**Comment by jinzishuai** [comment]
## 2.1 missing cuda

```
(.venv) seki@LAPTOP-0OTVHE5I:~/ZeroBox/src/apex$ pip install -v --disable-pip-version-check --no-cache-dir --global-option="--cpp_ext" --global-option="--cuda_ext" ./
/mnt/c/ZeroBox/src/3DC-Seg/.venv/lib/python3.8/site-packages/pip/_internal/commands/install.py:255: UserWarning: Disabling all use of wheels due to the use of --build-option / --global-option / --install-option.
  cmdoptions.check_install_build_global(options)
Non-user install because user site-packages disabled
Created temporary directory: /tmp/pip-ephem-wheel-cache-uqq7pwmh
Created temporary directory: /tmp/pip-req-tracker-9feuro7a
Initialized build tracking at /tmp/pip-req-tracker-9feuro7a
Created build tracker: /tmp/pip-req-tracker-9feuro7a
Entered build tracker: /tmp/pip-req-tracker-9feuro7a
Created temporary directory: /tmp/pip-install-kzkbil6f
Processing /mnt/c/ZeroBox/src/apex
  Created temporary directory: /tmp/pip-req-build-djo5wjwa
  Added file:///mnt/c/ZeroBox/src/apex to build tracker '/tmp/pip-req-tracker-9feuro7a'
    Running setup.py (path:/tmp/pip-req-build-djo5wjwa/setup.py) egg_info for package from file:///mnt/c/ZeroBox/src/apex
    Running command python setup.py egg_info
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-djo5wjwa/setup.py", line 35, in <module>
        _, bare_metal_major, _ = get_cuda_bare_metal_version(cpp_extension.CUDA_HOME)
      File "/tmp/pip-req-build-djo5wjwa/setup.py", line 14, in get_cuda_bare_metal_version
        raw_output = subprocess.check_output([cuda_dir + "/bin/nvcc", "-V"], universal_newlines=True)
    TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'

    Warning: Torch did not find available GPUs on this system.
     If your intention is to cross-compile, this is not an error.
    By default, Apex will cross-compile for Pascal (compute capabilities 6.0, 6.1, 6.2),
    Volta (compute capability 7.0), Turing (compute capability 7.5),
    and, if the CUDA version is >= 11.0, Ampere (compute capability 8.0).
    If you wish to cross-compile for a single specific architecture,
    export TORCH_CUDA_ARCH_LIST="compute capability" before running setup.py.

Cleaning up...
  Removing source in /tmp/pip-req-build-djo5wjwa
Removed file:///mnt/c/ZeroBox/src/apex from build tracker '/tmp/pip-req-tracker-9feuro7a'
Removed build tracker: '/tmp/pip-req-tracker-9feuro7a'
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
Exception information:
Traceback (most recent call last):
  File "/mnt/c/ZeroBox/src/3DC-Seg/.venv/lib/python3.8/site-packages/pip/_internal/cli/base_command.py", line 186, in _main
    status = self.run(options, args)
  File "/mnt/c/ZeroBox/src/3DC-Seg/.venv/lib/python3.8/site-packages/pip/_internal/commands/install.py", line 357, in run
    resolver.resolve(requirement_set)
  File "/mnt/c/ZeroBox/src/3DC-Seg/.venv/lib/python3.8/site-packages/pip/_internal/legacy_resolve.py", line 177, in resolve
    discovered_reqs.extend(self._resolve_one(requirement_set, req))
  File "/mnt/c/ZeroBox/src/3DC-Seg/.venv/lib/python3.8/site-packages/pip/_internal/legacy_resolve.py", line 333, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/mnt/c/ZeroBox/src/3DC-Seg/.venv/lib/python3.8/site-packages/pip/_internal/legacy_resolve.py", line 282, in _get_abstract_dist_for
    abstract_dist = self.preparer.prepare_linked_requirement(req)
  File "/mnt/c/ZeroBox/src/3DC-Seg/.venv/lib/python3.8/site-packages/pip/_internal/operations/prepare.py", line 515, in prepare_linked_requirement
    abstract_dist = _get_prepared_distribution(
  File "/mnt/c/ZeroBox/src/3DC-Seg/.venv/lib/python3.8/site-packages/pip/_internal/operations/prepare.py", line 95, in _get_prepared_distribution
    abstract_dist.prepare_distribution_metadata(finder, build_isolation)
  File "/mnt/c/ZeroBox/src/3DC-Seg/.venv/lib/python3.8/site-packages/pip/_internal/distributions/sdist.py", line 40, in prepare_distribution_metadata
    self.req.prepare_metadata()
  File "/mnt/c/ZeroBox/src/3DC-Seg/.venv/lib/python3.8/site-packages/pip/_internal/req/req_install.py", line 564, in prepare_metadata
    self.metadata_directory = self._generate_metadata()
  File "/mnt/c/ZeroBox/src/3DC-Seg/.venv/lib/python3.8/site-packages/pip/_internal/req/req_install.py", line 538, in _generate_metadata
    return generate_metadata_legacy(
  File "/mnt/c/ZeroBox/src/3DC-Seg/.venv/lib/python3.8/site-packages/pip/_internal/operations/build/metadata_legacy.py", line 115, in generate_metadata
    call_subprocess(
  File "/mnt/c/ZeroBox/src/3DC-Seg/.venv/lib/python3.8/site-packages/pip/_internal/utils/subprocess.py", line 242, in call_subprocess
    raise InstallationError(exc_msg)
pip._internal.exceptions.InstallationError: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
(.venv) seki@LAPTOP-0OTVHE5I:~/ZeroBox/src/apex$
```

**Comment by jinzishuai** [comment]
## 2.2 Try python-only build

```
pip install -v --disable-pip-version-check --no-cache-dir ./
```

Still failed with the same error.

**Comment by jinzishuai** [comment]
# 3. Install nvcc first

```
sudo apt install nvidia-cuda-toolkit
```

resulting
```
(.venv) seki@LAPTOP-0OTVHE5I:~/ZeroBox/src/apex$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Sun_Jul_28_19:07:16_PDT_2019
Cuda compilation tools, release 10.1, V10.1.243
```

**Comment by jinzishuai** [comment]
# Then `pip install -v --no-cache-dir .` worked

```
...
  adding 'apex-0.1.dist-info/LICENSE'
  adding 'apex-0.1.dist-info/METADATA'
  adding 'apex-0.1.dist-info/WHEEL'
  adding 'apex-0.1.dist-info/top_level.txt'
  adding 'apex-0.1.dist-info/RECORD'
  removing build/bdist.linux-x86_64/wheel
done
  Created wheel for apex: filename=apex-0.1-py3-none-any.whl size=198536 sha256=58a105528a0c0fbb1d0cb0b03940006659609e24f218fbeb17d30c5ee69f9d05
  Stored in directory: /tmp/pip-ephem-wheel-cache-3rn9_6em/wheels/80/a0/dd/cb1450e5fa90aedb826eb1aae1197b702557bfe05573834d1f
Successfully built apex
Installing collected packages: apex
  Created temporary directory: /tmp/pip-unpacked-wheel-c9ehu_1z

Successfully installed apex-0.1
Cleaning up...
  Removing source in /tmp/pip-req-build-9stgojvq
Removed build tracker: '/tmp/pip-req-tracker-y2u_ih_r'
```

And we have it in pip
```
(.venv) seki@LAPTOP-0OTVHE5I:~/ZeroBox/src/apex$ pip list|grep apex
apex            0.1
```

**Comment by jinzishuai** [comment]
# No longer having the apex issue

```
(.venv) seki@LAPTOP-0OTVHE5I:~/ZeroBox/src/3DC-Seg$ python main.py -c run_configs/bmvc_fbms.yaml --task infer --wts ./bmvc_final.pth
Traceback (most recent call last):
  File "main.py", line 334, in <module>
    trainer = Trainer(args, port)
  File "main.py", line 40, in __init__
    assert os.path.exists('saved_models'), "Create a path to save the trained models: <default: ./saved_models> "
AssertionError: Create a path to save the trained models: <default: ./saved_models>
```
