### ISSUE TITLE
install apex with GPU on WSL for Windows

### ISSUE THREAD

**Issue by jinzishuai** [jinzishuai/3DC-Seg#3]
follow up from https://github.com/jinzishuai/3DC-Seg/issues/2

**Comment by jinzishuai** [comment]
```
(.venv) seki@LAPTOP-0OTVHE5I:~/ZeroBox/src/apex$ pip install -v --disable-pip-version-check --no-cache-dir --global-option="--cpp_ext" --global-option="--cuda_ext" ./
```

**Comment by jinzishuai** [comment]
![image](https://user-images.githubusercontent.com/1074685/113970051-5c850280-97f3-11eb-8b51-dd136f098c17.png)

**Comment by jinzishuai** [comment]
Blocked due to a known WSL bug
https://github.com/jinzishuai/personal-repo/issues/335#issuecomment-815453131

**Comment by jinzishuai** [comment]
# Rebuild after WSL updated to Build 21359 

See https://github.com/jinzishuai/personal-repo/issues/335#issuecomment-822069807

```
(.venv) seki@LAPTOP-0OTVHE5I:~/ZeroBox/src/apex$ pip install -v --disable-pip-version-check --no-cache-dir --global-option="--cpp_ext" --global-option="--cuda_ext" ./
```

**Comment by jinzishuai** [comment]
## cuda version mismatch

```
Installing collected packages: apex
  Attempting uninstall: apex
    Found existing installation: apex 0.1
    Uninstalling apex-0.1:
      Created temporary directory: /mnt/c/ZeroBox/src/3DC-Seg/.venv/lib/python3.8/site-packages/~pex-0.1.dist-info
      Removing file or directory /mnt/c/ZeroBox/src/3DC-Seg/.venv/lib/python3.8/site-packages/apex-0.1.dist-info/
      Created temporary directory: /mnt/c/ZeroBox/src/3DC-Seg/.venv/lib/python3.8/site-packages/~pex
      Removing file or directory /mnt/c/ZeroBox/src/3DC-Seg/.venv/lib/python3.8/site-packages/apex/
      Successfully uninstalled apex-0.1
  Created temporary directory: /tmp/pip-record-j1h86wy_
    Running command /mnt/c/ZeroBox/src/3DC-Seg/.venv/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-4k9bvca6/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-4k9bvca6/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' --cpp_ext --cuda_ext install --record /tmp/pip-record-j1h86wy_/install-record.txt --single-version-externally-managed --compile --install-headers /mnt/c/ZeroBox/src/3DC-Seg/.venv/include/site/python3.8/apex


    torch.__version__  = 1.5.1+cu92


    /tmp/pip-req-build-4k9bvca6/setup.py:67: UserWarning: Option --pyprof not specified. Not installing PyProf dependencies!
      warnings.warn("Option --pyprof not specified. Not installing PyProf dependencies!")

    Compiling cuda extensions with
    nvcc: NVIDIA (R) Cuda compiler driver
    Copyright (c) 2005-2019 NVIDIA Corporation
    Built on Sun_Jul_28_19:07:16_PDT_2019
    Cuda compilation tools, release 10.1, V10.1.243
    from /usr/bin

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-4k9bvca6/setup.py", line 171, in <module>
        check_cuda_torch_binary_vs_bare_metal(torch.utils.cpp_extension.CUDA_HOME)
      File "/tmp/pip-req-build-4k9bvca6/setup.py", line 102, in check_cuda_torch_binary_vs_bare_metal
        raise RuntimeError("Cuda extensions are being compiled with a version of Cuda that does " +
    RuntimeError: Cuda extensions are being compiled with a version of Cuda that does not match the version used to compile Pytorch binaries.  Pytorch binaries were compiled with Cuda 9.2.
    In some cases, a minor-version mismatch will not cause later errors:  https://github.com/NVIDIA/apex/pull/323#discussion_r287021798.  You can try commenting out this check (at your own risk).
    Running setup.py install for apex ... error
  Rolling back uninstall of apex
  Moving to /mnt/c/ZeroBox/src/3DC-Seg/.venv/lib/python3.8/site-packages/apex-0.1.dist-info/
   from /mnt/c/ZeroBox/src/3DC-Seg/.venv/lib/python3.8/site-packages/~pex-0.1.dist-info
  Moving to /mnt/c/ZeroBox/src/3DC-Seg/.venv/lib/python3.8/site-packages/apex/
   from /mnt/c/ZeroBox/src/3DC-Seg/.venv/lib/python3.8/site-packages/~pex
  Replacing /mnt/c/ZeroBox/src/3DC-Seg/.venv/lib/python3.8/site-packages/apex-0.1.dist-info/ from /mnt/c/ZeroBox/src/3DC-Seg/.venv/lib/python3.8/site-packages/~pex-0.1.dist-info
  Replacing /mnt/c/ZeroBox/src/3DC-Seg/.venv/lib/python3.8/site-packages/apex/ from /mnt/c/ZeroBox/src/3DC-Seg/.venv/lib/python3.8/site-packages/~pex
Cleaning up...
  Removing source in /tmp/pip-req-build-4k9bvca6
Removed build tracker: '/tmp/pip-req-tracker-v3apyd_u'
ERROR: Command errored out with exit status 1: /mnt/c/ZeroBox/src/3DC-Seg/.venv/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-4k9bvca6/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-4k9bvca6/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' --cpp_ext --cuda_ext install --record /tmp/pip-record-j1h86wy_/install-record.txt --single-version-externally-managed --compile --install-headers /mnt/c/ZeroBox/src/3DC-Seg/.venv/include/site/python3.8/apex Check the logs for full command output.
Exception information:
Traceback (most recent call last):
  File "/mnt/c/ZeroBox/src/3DC-Seg/.venv/lib/python3.8/site-packages/pip/_internal/cli/base_command.py", line 186, in _main
    status = self.run(options, args)
  File "/mnt/c/ZeroBox/src/3DC-Seg/.venv/lib/python3.8/site-packages/pip/_internal/commands/install.py", line 421, in run
    installed = install_given_reqs(
  File "/mnt/c/ZeroBox/src/3DC-Seg/.venv/lib/python3.8/site-packages/pip/_internal/req/__init__.py", line 67, in install_given_reqs
    requirement.install(
  File "/mnt/c/ZeroBox/src/3DC-Seg/.venv/lib/python3.8/site-packages/pip/_internal/req/req_install.py", line 820, in install
    install_legacy(
  File "/mnt/c/ZeroBox/src/3DC-Seg/.venv/lib/python3.8/site-packages/pip/_internal/operations/install/legacy.py", line 70, in install
    runner(
  File "/mnt/c/ZeroBox/src/3DC-Seg/.venv/lib/python3.8/site-packages/pip/_internal/utils/subprocess.py", line 271, in runner
    call_subprocess(
  File "/mnt/c/ZeroBox/src/3DC-Seg/.venv/lib/python3.8/site-packages/pip/_internal/utils/subprocess.py", line 242, in call_subprocess
    raise InstallationError(exc_msg)
pip._internal.exceptions.InstallationError: Command errored out with exit status 1: /mnt/c/ZeroBox/src/3DC-Seg/.venv/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-4k9bvca6/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-4k9bvca6/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' --cpp_ext --cuda_ext install --record /tmp/pip-record-j1h86wy_/install-record.txt --single-version-externally-managed --compile --install-headers /mnt/c/ZeroBox/src/3DC-Seg/.venv/include/site/python3.8/apex Check the logs for full command output.
```

**Comment by jinzishuai** [comment]
This problem is very similar to https://github.com/jinzishuai/personal-repo/issues/346

### We need to install pytorch with CUDA-11

Current torch
```
(.venv) seki@LAPTOP-0OTVHE5I:~/ZeroBox/src/3DC-Seg$ pip list|grep torch
torch           1.5.1+cu92
torchsummary    1.5.1
torchvision     0.6.1+cu92
```
But we need to do

```
pip install torch==1.7.0+cu110 torchvision==0.8.1+cu110  -f https://download.pytorch.org/whl/torch_stabl
e.html
```

**Comment by jinzishuai** [comment]
# Still a problem with wrong CUDA version due to another nvcc existing

```
(.venv) seki@LAPTOP-0OTVHE5I:~/ZeroBox/src/apex$ /usr/local/cuda/bin/nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2020 NVIDIA Corporation
Built on Wed_Jul_22_19:09:09_PDT_2020
Cuda compilation tools, release 11.0, V11.0.221
Build cuda_11.0_bu.TC445_37.28845127_0
(.venv) seki@LAPTOP-0OTVHE5I:~/ZeroBox/src/apex$ which nvcc
/usr/bin/nvcc
(.venv) seki@LAPTOP-0OTVHE5I:~/ZeroBox/src/apex$ /usr/bin/nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Sun_Jul_28_19:07:16_PDT_2019
Cuda compilation tools, release 10.1, V10.1.243
```
The error is
![image](https://user-images.githubusercontent.com/1074685/115163214-189cc380-a065-11eb-8bed-ed6bdfc8af67.png)

**Comment by jinzishuai** [comment]
solution:
```
sudo apt remove nvidia-cuda-toolkit
```

**Comment by jinzishuai** [comment]
Worked!
```
Successfully installed apex-0.1
Cleaning up...
  Removing source in /tmp/pip-req-build-my1jjtn7
Removed build tracker: '/tmp/pip-req-tracker-0by0d4t6'
(.venv) seki@LAPTOP-0OTVHE5I:~/ZeroBox/src/apex$
```
