### ISSUE TITLE
understand dataloader

### ISSUE THREAD

**Issue by jinzishuai** [jinzishuai/3DC-Seg#4]
# 6 dataset classes

![image](https://user-images.githubusercontent.com/1074685/114286176-a51e0500-9a19-11eb-9168-dae6cd9ca5f6.png)

**Comment by jinzishuai** [comment]
# Directly run dataset python code

```
(3dc-seg) seki@gpu:~/src/3DC-Seg$ export PYTHONPATH=$(pwd):$PYTHONPATH
(3dc-seg) seki@gpu:~/src/3DC-Seg$ python datasets/fbms/Fbms.py
Dataset size: 0
```

**Comment by jinzishuai** [comment]
```
(3dc-seg) seki@gpu:~/src/3DC-Seg$ python datasets/fbms/Fbms.py
Traceback (most recent call last):
  File "datasets/fbms/Fbms.py", line 100, in <module>
    fbms = FBMSDataset(root=FBMS_ROOT,
  File "datasets/fbms/Fbms.py", line 20, in __init__
    super(FBMSDataset, self).__init__(root, mode, resize_mode, resize_shape, tw, max_temporal_gap, num_classes)
  File "/home/seki/src/3DC-Seg/datasets/davis/Davis.py", line 20, in __init__
    super(Davis, self).__init__(root, mode, resize_mode, resize_shape, tw, max_temporal_gap, num_classes)
  File "/home/seki/src/3DC-Seg/datasets/BaseDataset.py", line 128, in __init__
    super(VideoDataset, self).__init__(root, mode, resize_mode, resize_shape)
  File "/home/seki/src/3DC-Seg/datasets/BaseDataset.py", line 34, in __init__
    self.create_sample_list()
  File "datasets/fbms/Fbms.py", line 69, in create_sample_list
    self.video_frames[sequence] = [int(f.split("/")[-1].split("_")[-1].split(".")[0])
  File "datasets/fbms/Fbms.py", line 69, in <listcomp>
    self.video_frames[sequence] = [int(f.split("/")[-1].split("_")[-1].split(".")[0])
ValueError: invalid literal for int() with base 10: 'tennis896'
```

**Comment by jinzishuai** [comment]
# move the problematic tennis folder and it started to work

```
seki@gpu:~/ZeroBox/FBMS_Testset/Testset$ mv tennis/ ~/
```

the code then works

**Comment by jinzishuai** [comment]
## short run: keep only camel01

```
seki@gpu:~/ZeroBox/FBMS_Testset/Testset$ rm -fR cars10  cars5   cats03  dogs01  farm01      goats01   horses04  lion01    marple2  marple6  marple9   people1  rabbits02  rabbits04 cars1    cars4   cats01  cats06  dogs02  giraffes01  horses02  horses05  marple12  marple4  marple7  people03  people2  rabbits03
seki@gpu:~/ZeroBox/FBMS_Testset/Testset$ ls
camel01
```

The output is 2 lines per image and we have a total of 100 images
```
(3dc-seg) seki@gpu:~/src/3DC-Seg$ python datasets/fbms/Fbms.py  >camel01.log
(3dc-seg) seki@gpu:~/src/3DC-Seg$ ls
3dc-seg    __pycache__     camel01.log  datasets            loss     network           results      run_scripts   util.py
README.md  bmvc_final.pth  config       inference_handlers  main.py  requirements.txt  run_configs  saved_models  utils
(3dc-seg) seki@gpu:~/src/3DC-Seg$ wc camel01.log
  201  3717 24366 camel01.log
(3dc-seg) seki@gpu:~/src/3DC-Seg$ head camel01.log
Dataset size: 100
[{'support_indices': array([39, 40, 41, 42, 43, 44, 45, 46]), 'video': 'camel01', 'num_frames': 100, 'num_objects': 1, 'shape': (540, 680), 'gt_frames': [], 'pad': ((0, 0), (5, 5))}]
Image Max 1.0, Image Min 0.0 Target max 0.0, Target Min 0.0
[{'support_indices': array([52, 53, 54, 55, 56, 57, 58, 59]), 'video': 'camel01', 'num_frames': 100, 'num_objects': 1, 'shape': (540, 680), 'gt_frames': [], 'pad': ((0, 0), (5, 5))}]
Image Max 1.0, Image Min 0.0 Target max 0.0, Target Min 0.0
[{'support_indices': array([48, 49, 50, 51, 52, 53, 54, 55]), 'video': 'camel01', 'num_frames': 100, 'num_objects': 1, 'shape': (540, 680), 'gt_frames': [], 'pad': ((0, 0), (5, 5))}]
Image Max 1.0, Image Min 0.0 Target max 0.0, Target Min 0.0
[{'support_indices': array([85, 86, 87, 88, 89, 90, 91, 92]), 'video': 'camel01', 'num_frames': 100, 'num_objects': 1, 'shape': (540, 680), 'gt_frames': [], 'pad': ((0, 0), (5, 5))}]
Image Max 1.0, Image Min 0.0 Target max 0.0, Target Min 0.0
[{'support_indices': array([46, 47, 48, 49, 50, 51, 52, 53]), 'video': 'camel01', 'num_frames': 100, 'num_objects': 1, 'shape': (540, 680), 'gt_frames': [], 'pad': ((0, 0), (5, 5))}]
(3dc-seg) seki@gpu:~/src/3DC-Seg$
```

**Comment by jinzishuai** [comment]
# How should training data look like?

## Revised New Folder Tree

```
seki@gpu:~/ZeroBox$ tree -d
.
└── FBMS_Dataset
    ├── Testset
    │   └── camel01
    │       └── GroundTruth
    └── Trainingset
        └── cars1
            └── GroundTruth

7 directories
seki@gpu:~/ZeroBox$
```

**Comment by jinzishuai** [comment]
```
(3dc-seg) seki@gpu:~/src/3DC-Seg$ python datasets/fbms/Fbms.py
Dataset size: 19
[{'support_indices': array([17, 17, 17, 17, 17, 17, 17, 18]), 'video': 'cars1', 'num_frames': 19, 'num_objects': 1, 'shape': (480, 640), 'gt_frames': [], 'pad': ((0, 0), (5, 5))}]
Image Max 1.0, Image Min 0.0 Target max 0.0, Target Min 0.0
[{'support_indices': array([15, 15, 15, 15, 15, 16, 17, 18]), 'video': 'cars1', 'num_frames': 19, 'num_objects': 1, 'shape': (480, 640), 'gt_frames': [], 'pad': ((0, 0), (5, 5))}]
Image Max 1.0, Image Min 0.0 Target max 0.0, Target Min 0.0
[{'support_indices': array([13, 13, 13, 14, 15, 16, 17, 18]), 'video': 'cars1', 'num_frames': 19, 'num_objects': 1, 'shape': (480, 640), 'gt_frames': [], 'pad': ((0, 0), (5, 5))}]
Image Max 1.0, Image Min 0.0 Target max 0.0, Target Min 0.0
[{'support_indices': array([ 8,  9, 10, 11, 12, 13, 14, 15]), 'video': 'cars1', 'num_frames': 19, 'num_objects': 1, 'shape': (480, 640), 'gt_frames': [], 'pad': ((0, 0), (5, 5))}]
Image Max 1.0, Image Min 0.0 Target max 0.0, Target Min 0.0
[{'support_indices': array([16, 16, 16, 16, 16, 16, 17, 18]), 'video': 'cars1', 'num_frames': 19, 'num_objects': 1, 'shape': (480, 640), 'gt_frames': [], 'pad': ((0, 0), (5, 5))}]
Image Max 1.0, Image Min 0.0 Target max 0.0, Target Min 0.0
[{'support_indices': array([ 4,  5,  6,  7,  8,  9, 10, 11]), 'video': 'cars1', 'num_frames': 19, 'num_objects': 1, 'shape': (480, 640), 'gt_frames': [], 'pad': ((0, 0), (5, 5))}]
Image Max 1.0, Image Min 0.0 Target max 0.0, Target Min 0.0
[{'support_indices': array([18, 18, 18, 18, 18, 18, 18, 18]), 'video': 'cars1', 'num_frames': 19, 'num_objects': 1, 'shape': (480, 640), 'gt_frames': [], 'pad': ((0, 0), (5, 5))}]
Image Max 1.0, Image Min 0.0 Target max 0.0, Target Min 0.0
[{'support_indices': array([14, 14, 14, 14, 15, 16, 17, 18]), 'video': 'cars1', 'num_frames': 19, 'num_objects': 1, 'shape': (480, 640), 'gt_frames': [], 'pad': ((0, 0), (5, 5))}]
Image Max 1.0, Image Min 0.0 Target max 0.0, Target Min 0.0
[{'support_indices': array([12, 12, 13, 14, 15, 16, 17, 18]), 'video': 'cars1', 'num_frames': 19, 'num_objects': 1, 'shape': (480, 640), 'gt_frames': [], 'pad': ((0, 0), (5, 5))}]
Image Max 1.0, Image Min 0.0 Target max 0.0, Target Min 0.0
[{'support_indices': array([2, 3, 4, 5, 6, 7, 8, 9]), 'video': 'cars1', 'num_frames': 19, 'num_objects': 1, 'shape': (480, 640), 'gt_frames': [], 'pad': ((0, 0), (5, 5))}]
Image Max 1.0, Image Min 0.0 Target max 0.0, Target Min 0.0
[{'support_indices': array([ 9, 10, 11, 12, 13, 14, 15, 16]), 'video': 'cars1', 'num_frames': 19, 'num_objects': 1, 'shape': (480, 640), 'gt_frames': [], 'pad': ((0, 0), (5, 5))}]
Image Max 1.0, Image Min 0.0 Target max 0.0, Target Min 0.0
[{'support_indices': array([ 6,  7,  8,  9, 10, 11, 12, 13]), 'video': 'cars1', 'num_frames': 19, 'num_objects': 1, 'shape': (480, 640), 'gt_frames': [], 'pad': ((0, 0), (5, 5))}]
Image Max 1.0, Image Min 0.0 Target max 0.0, Target Min 0.0
[{'support_indices': array([ 5,  6,  7,  8,  9, 10, 11, 12]), 'video': 'cars1', 'num_frames': 19, 'num_objects': 1, 'shape': (480, 640), 'gt_frames': [], 'pad': ((0, 0), (5, 5))}]
Image Max 1.0, Image Min 0.0 Target max 0.0, Target Min 0.0
[{'support_indices': array([10, 11, 12, 13, 14, 15, 16, 17]), 'video': 'cars1', 'num_frames': 19, 'num_objects': 1, 'shape': (480, 640), 'gt_frames': [], 'pad': ((0, 0), (5, 5))}]
Image Max 1.0, Image Min 0.0 Target max 0.0, Target Min 0.0
[{'support_indices': array([19, 19, 19, 19, 19, 19, 19, 19]), 'video': 'cars1', 'num_frames': 19, 'num_objects': 1, 'shape': (480, 640), 'gt_frames': [], 'pad': ((0, 0), (5, 5))}]
Image Max 1.0, Image Min 0.0 Target max 0.0, Target Min 0.0
[{'support_indices': array([11, 12, 13, 14, 15, 16, 17, 18]), 'video': 'cars1', 'num_frames': 19, 'num_objects': 1, 'shape': (480, 640), 'gt_frames': [], 'pad': ((0, 0), (5, 5))}]
Image Max 1.0, Image Min 0.0 Target max 0.0, Target Min 0.0
[{'support_indices': array([1, 2, 3, 4, 5, 6, 7, 8]), 'video': 'cars1', 'num_frames': 19, 'num_objects': 1, 'shape': (480, 640), 'gt_frames': [], 'pad': ((0, 0), (5, 5))}]
Image Max 1.0, Image Min 0.0 Target max 0.0, Target Min 0.0
[{'support_indices': array([ 3,  4,  5,  6,  7,  8,  9, 10]), 'video': 'cars1', 'num_frames': 19, 'num_objects': 1, 'shape': (480, 640), 'gt_frames': [], 'pad': ((0, 0), (5, 5))}]
Image Max 1.0, Image Min 0.0 Target max 0.0, Target Min 0.0
[{'support_indices': array([ 7,  8,  9, 10, 11, 12, 13, 14]), 'video': 'cars1', 'num_frames': 19, 'num_objects': 1, 'shape': (480, 640), 'gt_frames': [], 'pad': ((0, 0), (5, 5))}]
Image Max 1.0, Image Min 0.0 Target max 0.0, Target Min 0.0
(3dc-seg) seki@gpu:~/src/3DC-Seg$
```

**Comment by jinzishuai** [comment]
# Testing multiple folders

```
seki@gpu:~/ZeroBox/FBMS_Dataset$ tree -d
.
├── Testset
│   └── camel01
│       └── GroundTruth
└── Trainingset
    ├── cars1
    │   └── GroundTruth
    └── cars5

7 directories
```
##  Training set

```
(3dc-seg) seki@gpu:~/src/3DC-Seg$ python datasets/fbms/Fbms.py
Dataset size: 55
[{'support_indices': array([17, 17, 17, 17, 17, 17, 17, 18]), 'video': 'cars1', 'num_frames': 19, 'num_objects': 1, 'shape': (480, 640), 'gt_frames': [], 'pad': ((0, 0), (5, 5))}]
Image Max 1.0, Image Min 0.0 Target max 0.0, Target Min 0.0
...


Image Max 1.0, Image Min 0.0 Target max 0.0, Target Min 0.0
[{'support_indices': array([ 7,  8,  9, 10, 11, 12, 13, 14]), 'video': 'cars1', 'num_frames': 19, 'num_objects': 1, 'shape': (480, 640), 'gt_frames': [], 'pad': ((0, 0), (5, 5))}]
Image Max 1.0, Image Min 0.0 Target max 0.0, Target Min 0.0
[{'support_indices': array([21, 22, 23, 24, 25, 26, 27, 28]), 'video': 'cars5', 'num_frames': 36, 'num_objects': 1, 'shape': (480, 640), 'gt_frames': [], 'pad': ((0, 0), (5, 5))}]
```
